spring:
  datasource:
      driver-class-name : com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/kamyam?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root

mybatis:
  mapperLocations: classpath*:mapper*/**/*.xml